consumer_key: <%= ENV['HTN_CONSUMER_KEY'] %>
consumer_secret: <%= ENV['HTN_CONSUMER_SECRET'] %>
access_token: <%= ENV['HTN_ACCESS_TOKEN'] %>
access_token_secret: <%= ENV['HTN_ACCESS_TOKEN_SECRET'] %>
user_id: <%= ENV['HTN_USER_ID'] %>
blog_id: <%= ENV['HTN_BLOG_ID'] %>
